#ifndef _CONST_
#define _CONST_

#define TEST_LEVEL LEVEL_FINAL3

#define LEVEL1 1
#define LEVEL2 2
#define LEVEL3 3
#define LEVEL4 4
#define LEVEL5 5
#define LEVEL_FINAL0 10 //一次穿两个测试，高度与比赛不同
#define LEVEL_FINAL1 11 //一次穿一个测试
#define LEVEL_FINAL2 12 //一次穿两个
#define LEVEL_FINAL3 13 //一次穿一个

#define CONTROL_FREQUENCY 50.0f

#define P_I 3.14159

#define MAX_MSG_LENGTH 0x9FFF
#define HEAD 0xAAAA
#define TAIL 0xDDDD

#define MAX_VEC_SIZE 40
//send msg type
#define HEART_BEAT_MSG 0
#define IMG_MSG 1
#define POSITION_NED_MSG 2
#define VELOCITY_BODY_MSG 3
#define ATTITUDE_MSG 4
#define INPUT_ATTITUDE_MSG 5
#define VEHICLE_STATUS_MSG 6
#define LOG_MSG 7
#define REFERENCE_DOWN_MSG 8
#define TARGET_MSG 9
#define REFERENCE_NE_MSG 10
#define CONTROL_STATUS_MSG 11
#define POS_XY_ERR_MSG 21

#define MISSION_COMMAND_MSG 15

#define VISION_FAIL_TOLERENCE 25 //500ms
#define OPEN_LOOP_TOLERENCE 25 //500ms
#define OPEN_LOOP_PITCH_DEG -15

#define FIRST_RING_DIAMETER_M 2.5
#define SECOND_RING_DIAMETER_M 2
#define THIRD_RING_DIAMETER_M 2

#if TEST_LEVEL == LEVEL_FINAL0 || TEST_LEVEL == LEVEL_FINAL1 || TEST_LEVEL == LEVEL_FINAL2 || TEST_LEVEL == LEVEL_FINAL3
#define SAFE_QUIT_COMMAND -2
#define FORCE_QUIT_COMMAND -1
#define WAIT_COMMAND 0
#define INIT_MISSION 99
#define TAKEOFF_MISSION 2
#define SETPOINT_CLIMB_MISSION 3 

#if TEST_LEVEL == LEVEL_FINAL0 ||TEST_LEVEL == LEVEL_FINAL2
#define SEARCH_TARGET12_MISSION 5
#define AJUSTPOSITION_MISSION 6
#define THROUGH_TARGET12_MISSION 7
#if TEST_LEVEL == LEVEL_FINAL0 
#define TARGET1_HEIGHT 1.0f
#define TARGET2_HEIGHT 1.0f
#define TARGET3_HEIGHT 1.0f
#endif
#if TEST_LEVEL == LEVEL_FINAL2 
#define TARGET1_HEIGHT 4.0f
#define TARGET2_HEIGHT 6.0f
#define TARGET3_HEIGHT 3.0f
#endif

#endif

#if TEST_LEVEL == LEVEL_FINAL1 ||TEST_LEVEL == LEVEL_FINAL3
#define SEARCH_TARGET1_MISSION 6
#define THROUGH_TARGET1_MISSION 5
#define SEARCH_TARGET2_MISSION 4
#define THROUGH_TARGET2_MISSION 7
#if TEST_LEVEL == LEVEL_FINAL1
#define TARGET1_HEIGHT 1.0f
#define TARGET2_HEIGHT 1.0f
#define TARGET3_HEIGHT 1.0f
#endif
#if TEST_LEVEL == LEVEL_FINAL3
#define TARGET1_HEIGHT 4.0f
#define TARGET2_HEIGHT 6.0f
#define TARGET3_HEIGHT 3.0f
#endif
#endif

#define SEARCH_TARGET3_MISSION 8
#define THROUGH_TARGET3_MISSION 9
#define LAND_MISSION 13

#define FINISH 15
#define ALTITUDE_UPPER_BOUND 8
#else

#define ALTITUDE_UPPER_BOUND 3

#define SAFE_QUIT_COMMAND -2
#define FORCE_QUIT_COMMAND -1
#define ALTITUDE_STEP_COMMAND 0
#define ALTITUDE_STAY_MODE 1
#define FLOW_HOLD_COMMAND 2
#define FLOW_HOLD_MODE 3
#define VISION_CONTROL_COMMAND 4
#define WAIT_COMMAND 5
#define VISION_CONTROL_MODE 6
#define VISION_OPEN_LOOP_MODE 10
#define SEARCH_RING 11
#define BRAKING 12
#define VISION_CONTROL_MODE_YAW 13
#define MISSIONS_AUTO 99
#define VISION_COLLIMATION 14

#define FIRST_RING_DIAMETER_M 2.0
#define SECOND_RING_DIAMETER_M 1.8
#define THIRD_RING_DIAMETER_M 1.8

#endif

#endif